# Generated by Django 5.2.15 on 2026-06-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
