# Generated by Django 5.2.15 on 2026-06-15 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_alter_parents_address_alter_student_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.parents')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.teacher')),
            ],
        ),
    ]
