# Generated by Django 5.2.15 on 2026-06-15 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_alter_combinedchanges_parents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedchanges',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_combine', to='demoapp.teacher'),
        ),
    ]
