# Generated by Django 5.2.15 on 2026-06-15 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_alter_combinedchanges_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedchanges',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_combine', to='demoapp.student'),
        ),
    ]
