# Generated by Django 5.2.15 on 2026-06-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_alter_combinedchanges_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_M_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parents', models.ManyToManyField(blank=True, null=True, related_name='parents_mm', to='demoapp.parents')),
                ('student', models.ManyToManyField(related_name='student_mm', to='demoapp.student')),
                ('teacher', models.ManyToManyField(related_name='teacher_mm', to='demoapp.teacher')),
            ],
        ),
    ]
